import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav(){
return (
<nav className="flex w-full items-center justify-between p-4 text-x1 font-semibold border-b">
  <div>Logo</div>
  <div>Sign In</div>


</nav>
);

}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
      <TopNav/>
        {children}
      </body>
    </html>
  );
}
